import Button from '@/template/components/form/Button.vue';
import ButtonGroup from '@/template/components/form/ButtonGroup.vue';
import ButtonInfo from '@/template/components/form/ButtonInfo.vue';
import CheckBox from '@/template/components/form/CheckBox.vue';
import Col from '@/template/components/form/Col.vue';
import Divider from '@/template/components/form/Divider.vue';
import Form from '@/template/components/form/Form.vue';
import FormItem from '@/template/components/form/FormItem.vue';
import Input from '@/template/components/form/Input.vue';
import KDialog from '@/template/components/form/KDialog.vue';
import KOption from '@/template/components/form/KOption.vue';
import KRichText from '@/template/components/form/KRichText.vue';
import KStitokVue from '@/template/components/form/KStitok.vue';
import Aside from '@/template/components/form/layout/Aside.vue';
import Card from '@/template/components/form/layout/Card.vue';
import Container from '@/template/components/form/layout/Container.vue';
import Footer from '@/template/components/form/layout/Footer.vue';
import Header from '@/template/components/form/layout/Header.vue';
import Main from '@/template/components/form/layout/Main.vue';
import Row from '@/template/components/form/Row.vue';
import Select from '@/template/components/form/Select.vue';
import SvgCheckBox from '@/template/components/form/SvgCheckBox.vue';
import Wrapper from '@/template/components/form/Wrapper.vue';
import Table from '@/template/components/table/Table.vue';
import TableCell from '@/template/components/table/TableCell.vue';
import TableColumn from '@/template/components/table/TableColumn.vue';
import TableColumnHeader from '@/template/components/table/TableColumnHeader.vue';
import TableFrame from '@/template/components/table/TableFrame.vue';
import TableHeader from '@/template/components/table/TableHeader.vue';
import type { App } from 'vue';
import type { IdUpdateStatus } from './@types';
import KCheckBox3stateVue from './form/KCheckBox3state.vue';
import KCheckBoxVue from './form/CheckBox.vue';
import KColorPickerVue from './form/KColorPicker.vue';
import KDateIntervalPickerVue from './form/KDateInterval.vue';
import KDatePickerVue from './form/KDatePicker.vue';
import KDrawerVue from './form/KDrawer.vue';
import KIconVue from './form/KIcon.vue';
import KInputNumberVue from './form/KInputNumber.vue';
import KToolTipVue from './form/KToolTip.vue';
import KUploadVue from './form/KUpload.vue';
import KVirtualKeyboardVue from './form/KVirtualKeyboard/KVirtualKeyboard.vue';
import KCollapseVue from './form/layout/KCollapse.vue';
import KCollapseItemVue from './form/layout/KCollapseItem.vue';
import KTabPanelVue from './form/layout/KTabPanel.vue';
import KTabsVue from './form/layout/KTabs.vue';
import KMenuVue from './form/menu/KMenu.vue';
import KMenuItemVue from './form/menu/KMenuItem.vue';
import KSubMenuVue from './form/menu/KSubMenu.vue';
import TableColumnSelect from './table/TableColumnSelect.vue';

export default {
	install: (app: App): App => {
		app.component(Aside.name!, Aside);
		app.component(Container.name!, Container);
		app.component(Footer.name!, Footer);
		app.component(Header.name!, Header);
		app.component(Main.name!, Main);
		app.component(Input.name!, Input);
		app.component(Select.name!, Select);

		app.component(Form.name!, Form);
		app.component(FormItem.name!, FormItem);
		app.component(Wrapper.name!, Wrapper);
		app.component('KCol', Col);
		app.component('KRow', Row);
		app.component(Button.name!, Button);
		app.component(ButtonGroup.name!, ButtonGroup);
		app.component(ButtonInfo.name!, ButtonInfo);
		app.component(Table.name!, Table);
		app.component(TableColumn.name!, TableColumn);
		app.component(TableColumnHeader.name!, TableColumnHeader);
		app.component(TableCell.name!, TableCell);
		app.component(TableColumnSelect.name!, TableColumnSelect);
		app.component(TableHeader.name!, TableHeader);
		app.component(TableFrame.name!, TableFrame);
		app.component(Divider.name!, Divider);
		app.component(Card.name!, Card);
		app.component(CheckBox.name!, CheckBox);
		app.component(SvgCheckBox.name!, SvgCheckBox);
		app.component(KDialog.name!, KDialog);
		app.component('KTabPanel', KTabPanelVue);
		app.component('KTabs', KTabsVue);
		app.component('KRichText', KRichText);
		app.component('KUpload', KUploadVue);
		app.component('KIcon', KIconVue);
		app.component('KCollapse', KCollapseVue);
		app.component('kCollapseItem', KCollapseItemVue);
		app.component('kColorPicker', KColorPickerVue);
		app.component('kDatePicker', KDatePickerVue);
		app.component('KOption', KOption);
		app.component('KMenu', KMenuVue);
		app.component('KSubMenu', KSubMenuVue);
		app.component('KMenuItem', KMenuItemVue);
		app.component('KDrawer', KDrawerVue);
		app.component('KDateInterval', KDateIntervalPickerVue);
		app.component('KInputNumber', KInputNumberVue);
		app.component('KTooltip', KToolTipVue);
		app.component('k-check-box-3state', KCheckBox3stateVue);
		app.component('KStitok', KStitokVue);
		app.component('KVirtualKeyboard', KVirtualKeyboardVue);
		app.component('KCheckbox', KCheckBoxVue);
		return app;
	},
};

export function isIdUpdateStatus(payload: unknown): payload is IdUpdateStatus {
	return 'updateStatus' in (payload as IdUpdateStatus);
}
